[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "appdirs>=1.4.4",
    "rich>=13.9.4",
    "setuptools>=78.1.0",
]
